apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: docker.io/k8shop/frontend:v0.0.1
        imagePullPolicy: Always
        name: frontend
        envFrom:
        - secretRef:
            name: k8shop
      restartPolicy: Always
