kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0000
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0000
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0001
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0001
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0002
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0002
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0003
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0003
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0004
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0004
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0005
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0005
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0006
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0006
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0007
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0007
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0008
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0008
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: local0009
  spec:
    storageClassName: local-path
    capacity:
      storage: 100Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: /tmp/pv0009
